from __future__ import annotations

from dataclasses import dataclass


PRODUCT_URLS = {
    "opq32r": "https://www.shl.com/products/product-catalog/view/occupational-personality-questionnaire-opq32r/",
    "opq_ucf_report": "https://www.shl.com/products/product-catalog/view/opq-universal-competency-report-2-0/",
    "opq_leadership_report": "https://www.shl.com/products/product-catalog/view/opq-leadership-report/",
    "smart_interview_live_coding": "https://www.shl.com/products/product-catalog/view/smart-interview-live-coding/",
    "linux_programming": "https://www.shl.com/products/product-catalog/view/linux-programming-general/",
    "networking_implementation": "https://www.shl.com/products/product-catalog/view/networking-and-implementation-new/",
    "verify_g_plus": "https://www.shl.com/products/product-catalog/view/shl-verify-interactive-g/",
    "svar_spoken_english_us": "https://www.shl.com/products/product-catalog/view/svar-spoken-english-us-new/",
    "contact_center_call_sim": "https://www.shl.com/products/product-catalog/view/contact-center-call-simulation-new/",
    "entry_customer_service": "https://www.shl.com/products/product-catalog/view/entry-level-customer-serv-retail-and-contact-center/",
    "customer_service_phone_sim": "https://www.shl.com/products/product-catalog/view/customer-service-phone-simulation/",
    "verify_numerical": "https://www.shl.com/products/product-catalog/view/shl-verify-interactive-numerical-reasoning/",
    "financial_accounting": "https://www.shl.com/products/product-catalog/view/financial-accounting-new/",
    "basic_statistics": "https://www.shl.com/products/product-catalog/view/basic-statistics-new/",
    "graduate_scenarios": "https://www.shl.com/products/product-catalog/view/graduate-scenarios/",
    "global_skills_assessment": "https://www.shl.com/products/product-catalog/view/global-skills-assessment/",
    "global_skills_report": "https://www.shl.com/products/product-catalog/view/global-skills-development-report/",
    "opq_mq_sales_report": "https://www.shl.com/products/product-catalog/view/opq-mq-sales-report/",
    "sales_transformation_ic": "https://www.shl.com/products/product-catalog/view/salestransformationreport2-0-individualcontributor/",
    "dsi": "https://www.shl.com/products/product-catalog/view/dependability-and-safety-instrument-dsi/",
    "safety_dependability": "https://www.shl.com/products/product-catalog/view/safety-and-dependability-focus-8-0/",
    "workplace_health_safety": "https://www.shl.com/products/product-catalog/view/workplace-health-and-safety-new/",
    "hipaa_security": "https://www.shl.com/products/product-catalog/view/hipaa-security/",
    "medical_terminology": "https://www.shl.com/products/product-catalog/view/medical-terminology-new/",
    "word_365_essentials": "https://www.shl.com/products/product-catalog/view/microsoft-word-365-essentials-new/",
    "ms_excel": "https://www.shl.com/products/product-catalog/view/ms-excel-new/",
    "ms_word": "https://www.shl.com/products/product-catalog/view/ms-word-new/",
    "excel_365_sim": "https://www.shl.com/products/product-catalog/view/microsoft-excel-365-new/",
    "word_365_sim": "https://www.shl.com/products/product-catalog/view/microsoft-word-365-new/",
    "core_java_advanced": "https://www.shl.com/products/product-catalog/view/core-java-advanced-level-new/",
    "spring": "https://www.shl.com/products/product-catalog/view/spring-new/",
    "restful_web_services": "https://www.shl.com/products/product-catalog/view/restful-web-services-new/",
    "sql": "https://www.shl.com/products/product-catalog/view/sql-new/",
    "aws_development": "https://www.shl.com/products/product-catalog/view/amazon-web-services-aws-development-new/",
    "docker": "https://www.shl.com/products/product-catalog/view/docker-new/",
    "python": "https://www.shl.com/products/product-catalog/view/python-new/",
    "javascript": "https://www.shl.com/products/product-catalog/view/javascript-new/",
}


@dataclass(frozen=True)
class ProductBoostRule:
    label: str
    triggers: tuple[str, ...]
    product_keys: tuple[str, ...]
    boost: float


PRODUCT_BOOST_RULES: tuple[ProductBoostRule, ...] = (
    ProductBoostRule(
        "executive leadership",
        ("executive", "leadership", "cxo", "cxos", "director", "senior leadership"),
        ("opq32r", "opq_leadership_report", "opq_ucf_report"),
        75,
    ),
    ProductBoostRule(
        "rust systems networking engineer",
        ("rust", "networking", "systems engineer", "infrastructure", "linux"),
        (
            "smart_interview_live_coding",
            "linux_programming",
            "networking_implementation",
            "verify_g_plus",
            "opq32r",
        ),
        58,
    ),
    ProductBoostRule(
        "contact center customer support",
        (
            "contact center",
            "contact centre",
            "call center",
            "call centre",
            "customer support",
            "customer service",
            "inbound calls",
        ),
        (
            "svar_spoken_english_us",
            "contact_center_call_sim",
            "entry_customer_service",
            "customer_service_phone_sim",
        ),
        72,
    ),
    ProductBoostRule(
        "graduate trainee",
        ("graduate", "graduates", "trainee", "freshers", "fresh graduates"),
        ("verify_g_plus", "graduate_scenarios"),
        48,
    ),
    ProductBoostRule(
        "finance analyst",
        ("finance analyst", "financial analyst", "financial analysts", "finance"),
        ("verify_numerical", "financial_accounting", "basic_statistics", "opq32r"),
        66,
    ),
    ProductBoostRule(
        "skills audit reskilling",
        ("reskill", "re skill", "re-skill", "skills audit", "talent audit", "talent review"),
        ("global_skills_assessment", "global_skills_report"),
        74,
    ),
    ProductBoostRule(
        "sales",
        ("sales", "seller", "selling", "salesperson"),
        ("opq_mq_sales_report", "sales_transformation_ic", "opq32r"),
        58,
    ),
    ProductBoostRule(
        "safety plant reliability",
        (
            "safety",
            "plant operator",
            "plant operators",
            "procedure compliance",
            "reliability",
            "dependable",
            "dependability",
            "follows procedures",
            "follow procedures",
            "procedural discipline",
            "detail oriented",
            "cutting corners",
            "chemical facility",
            "frontline",
            "warehouse",
            "manufacturing",
        ),
        ("dsi", "safety_dependability", "workplace_health_safety"),
        78,
    ),
    ProductBoostRule(
        "healthcare hipaa medical admin",
        ("healthcare", "hipaa", "medical admin", "patient records", "medical terminology"),
        ("hipaa_security", "medical_terminology", "word_365_essentials", "dsi", "opq32r"),
        68,
    ),
    ProductBoostRule(
        "admin office skills",
        ("admin assistant", "admin assistants", "office skills", "excel", "word"),
        ("ms_excel", "ms_word", "opq32r", "excel_365_sim", "word_365_sim"),
        48,
    ),
    ProductBoostRule(
        "java",
        ("java", "core java"),
        ("core_java_advanced",),
        70,
    ),
    ProductBoostRule(
        "spring",
        ("spring",),
        ("spring",),
        70,
    ),
    ProductBoostRule(
        "sql",
        ("sql", "relational database", "relational databases"),
        ("sql",),
        70,
    ),
    ProductBoostRule(
        "aws",
        ("aws", "amazon web services", "cloud"),
        ("aws_development",),
        65,
    ),
    ProductBoostRule(
        "docker",
        ("docker", "container", "containers"),
        ("docker",),
        65,
    ),
    ProductBoostRule(
        "analytical problem solving",
        (
            "analytical",
            "problem solving",
            "numerical ability",
            "data analyst",
            "data analysts",
            "business analyst",
            "business analysts",
        ),
        ("verify_g_plus", "verify_numerical", "basic_statistics", "opq32r"),
        54,
    ),
    ProductBoostRule(
        "communication stakeholder teamwork adaptability",
        (
            "communication",
            "stakeholder management",
            "stakeholders",
            "teamwork",
            "adaptability",
            "customer facing",
            "customer-facing",
        ),
        ("opq32r", "global_skills_assessment"),
        45,
    ),
    ProductBoostRule(
        "leadership potential",
        ("leadership potential", "future managers", "future manager"),
        ("opq32r", "opq_leadership_report", "graduate_scenarios", "verify_g_plus"),
        62,
    ),
    ProductBoostRule(
        "compliance",
        ("compliance",),
        ("dsi", "workplace_health_safety", "hipaa_security", "opq32r"),
        36,
    ),
    ProductBoostRule(
        "software engineer",
        ("software engineer", "software engineers", "developer"),
        ("smart_interview_live_coding", "verify_g_plus", "opq32r"),
        42,
    ),
    ProductBoostRule(
        "python",
        ("python",),
        ("python",),
        70,
    ),
    ProductBoostRule(
        "javascript",
        ("javascript", "java script"),
        ("javascript",),
        70,
    ),
    ProductBoostRule(
        "cloud engineer",
        ("cloud engineer", "cloud engineers", "cloud native", "cloud-native"),
        ("aws_development", "docker", "verify_g_plus", "opq32r"),
        52,
    ),
    ProductBoostRule(
        "senior technical defaults",
        ("senior engineer", "senior ic", "architectural", "architecture", "mentor"),
        ("verify_g_plus", "opq32r"),
        36,
    ),
    ProductBoostRule(
        "add personality",
        ("add personality", "personality", "behavioural fit", "behavioral fit"),
        ("opq32r",),
        42,
    ),
    ProductBoostRule(
        "add cognitive reasoning",
        ("add cognitive", "cognitive", "reasoning", "verify g", "general ability"),
        ("verify_g_plus",),
        48,
    ),
)


STOPWORDS = frozenset(
    {
        "a",
        "an",
        "and",
        "are",
        "as",
        "at",
        "be",
        "but",
        "by",
        "can",
        "for",
        "from",
        "has",
        "have",
        "i",
        "in",
        "is",
        "it",
        "need",
        "of",
        "on",
        "or",
        "our",
        "should",
        "that",
        "the",
        "their",
        "they",
        "this",
        "to",
        "use",
        "we",
        "what",
        "who",
        "with",
    }
)
